modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="basedefense"
version="${file.jarVersion}"
displayName="Base Defense"
authors="sciwhiz12" 
description='''
Defending your base, defending against threats.
'''

[[dependencies.basedefense]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.basedefense]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
