modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"

[[mods]]
modId="basedefense"
version="${file.jarVersion}"
displayName="Base Defense"
authors="sciwhiz12" 
description='''
Defending your base, defending against threats.
'''

[[dependencies.basedefense]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.basedefense]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
